export interface TimezoneEntry {
  city: string;
  timezone: string;
  country: string;
  lat?: number;
  lng?: number;
}

export const TIMEZONE_LIST: TimezoneEntry[] = [
  { city: "Abidjan", timezone: "Africa/Abidjan", country: "CI", lat: 5.36, lng: -4.01 },
  { city: "Abu Dhabi", timezone: "Asia/Dubai", country: "AE", lat: 24.45, lng: 54.65 },
  { city: "Accra", timezone: "Africa/Accra", country: "GH", lat: 5.56, lng: -0.19 },
  { city: "Addis Ababa", timezone: "Africa/Addis_Ababa", country: "ET", lat: 9.02, lng: 38.75 },
  { city: "Adelaide", timezone: "Australia/Adelaide", country: "AU", lat: -34.93, lng: 138.60 },
  { city: "Almaty", timezone: "Asia/Almaty", country: "KZ", lat: 43.24, lng: 76.95 },
  { city: "Amman", timezone: "Asia/Amman", country: "JO", lat: 31.95, lng: 35.93 },
  { city: "Amsterdam", timezone: "Europe/Amsterdam", country: "NL", lat: 52.37, lng: 4.90 },
  { city: "Anchorage", timezone: "America/Anchorage", country: "US", lat: 61.22, lng: -149.90 },
  { city: "Ankara", timezone: "Europe/Istanbul", country: "TR", lat: 39.93, lng: 32.86 },
  { city: "Antananarivo", timezone: "Indian/Antananarivo", country: "MG", lat: -18.91, lng: 47.54 },
  { city: "Athens", timezone: "Europe/Athens", country: "GR", lat: 37.98, lng: 23.73 },
  { city: "Auckland", timezone: "Pacific/Auckland", country: "NZ", lat: -36.85, lng: 174.76 },
  { city: "Baghdad", timezone: "Asia/Baghdad", country: "IQ", lat: 33.31, lng: 44.37 },
  { city: "Bangkok", timezone: "Asia/Bangkok", country: "TH", lat: 13.76, lng: 100.50 },
  { city: "Barcelona", timezone: "Europe/Madrid", country: "ES", lat: 41.39, lng: 2.17 },
  { city: "Beijing", timezone: "Asia/Shanghai", country: "CN", lat: 39.90, lng: 116.40 },
  { city: "Beirut", timezone: "Asia/Beirut", country: "LB", lat: 33.89, lng: 35.50 },
  { city: "Belgrade", timezone: "Europe/Belgrade", country: "RS", lat: 44.79, lng: 20.47 },
  { city: "Berlin", timezone: "Europe/Berlin", country: "DE", lat: 52.52, lng: 13.41 },
  { city: "Bogota", timezone: "America/Bogota", country: "CO", lat: 4.71, lng: -74.07 },
  { city: "Brisbane", timezone: "Australia/Brisbane", country: "AU", lat: -27.47, lng: 153.03 },
  { city: "Brussels", timezone: "Europe/Brussels", country: "BE", lat: 50.85, lng: 4.35 },
  { city: "Bucharest", timezone: "Europe/Bucharest", country: "RO", lat: 44.43, lng: 26.10 },
  { city: "Budapest", timezone: "Europe/Budapest", country: "HU", lat: 47.50, lng: 19.04 },
  { city: "Buenos Aires", timezone: "America/Argentina/Buenos_Aires", country: "AR", lat: -34.60, lng: -58.38 },
  { city: "Cairo", timezone: "Africa/Cairo", country: "EG", lat: 30.04, lng: 31.24 },
  { city: "Calgary", timezone: "America/Edmonton", country: "CA", lat: 51.05, lng: -114.07 },
  { city: "Cape Town", timezone: "Africa/Johannesburg", country: "ZA", lat: -33.93, lng: 18.42 },
  { city: "Caracas", timezone: "America/Caracas", country: "VE", lat: 10.48, lng: -66.90 },
  { city: "Casablanca", timezone: "Africa/Casablanca", country: "MA", lat: 33.57, lng: -7.59 },
  { city: "Chicago", timezone: "America/Chicago", country: "US", lat: 41.88, lng: -87.63 },
  { city: "Colombo", timezone: "Asia/Colombo", country: "LK", lat: 6.93, lng: 79.84 },
  { city: "Copenhagen", timezone: "Europe/Copenhagen", country: "DK", lat: 55.68, lng: 12.57 },
  { city: "Dakar", timezone: "Africa/Dakar", country: "SN", lat: 14.72, lng: -17.47 },
  { city: "Dallas", timezone: "America/Chicago", country: "US", lat: 32.78, lng: -96.80 },
  { city: "Dar es Salaam", timezone: "Africa/Dar_es_Salaam", country: "TZ", lat: -6.79, lng: 39.28 },
  { city: "Darwin", timezone: "Australia/Darwin", country: "AU", lat: -12.46, lng: 130.84 },
  { city: "Delhi", timezone: "Asia/Kolkata", country: "IN", lat: 28.61, lng: 77.21 },
  { city: "Denver", timezone: "America/Denver", country: "US", lat: 39.74, lng: -104.99 },
  { city: "Dhaka", timezone: "Asia/Dhaka", country: "BD", lat: 23.81, lng: 90.41 },
  { city: "Doha", timezone: "Asia/Qatar", country: "QA", lat: 25.29, lng: 51.53 },
  { city: "Dubai", timezone: "Asia/Dubai", country: "AE", lat: 25.20, lng: 55.27 },
  { city: "Dublin", timezone: "Europe/Dublin", country: "IE", lat: 53.35, lng: -6.26 },
  { city: "Edmonton", timezone: "America/Edmonton", country: "CA", lat: 53.55, lng: -113.49 },
  { city: "Fiji", timezone: "Pacific/Fiji", country: "FJ", lat: -17.71, lng: 177.99 },
  { city: "Frankfurt", timezone: "Europe/Berlin", country: "DE", lat: 50.11, lng: 8.68 },
  { city: "Guatemala City", timezone: "America/Guatemala", country: "GT", lat: 14.63, lng: -90.51 },
  { city: "Halifax", timezone: "America/Halifax", country: "CA", lat: 44.65, lng: -63.57 },
  { city: "Hanoi", timezone: "Asia/Ho_Chi_Minh", country: "VN", lat: 21.03, lng: 105.85 },
  { city: "Havana", timezone: "America/Havana", country: "CU", lat: 23.11, lng: -82.37 },
  { city: "Helsinki", timezone: "Europe/Helsinki", country: "FI", lat: 60.17, lng: 24.94 },
  { city: "Ho Chi Minh City", timezone: "Asia/Ho_Chi_Minh", country: "VN", lat: 10.82, lng: 106.63 },
  { city: "Hong Kong", timezone: "Asia/Hong_Kong", country: "HK", lat: 22.32, lng: 114.17 },
  { city: "Honolulu", timezone: "Pacific/Honolulu", country: "US", lat: 21.31, lng: -157.86 },
  { city: "Houston", timezone: "America/Chicago", country: "US", lat: 29.76, lng: -95.37 },
  { city: "Istanbul", timezone: "Europe/Istanbul", country: "TR", lat: 41.01, lng: 28.98 },
  { city: "Jakarta", timezone: "Asia/Jakarta", country: "ID", lat: -6.21, lng: 106.85 },
  { city: "Johannesburg", timezone: "Africa/Johannesburg", country: "ZA", lat: -26.20, lng: 28.04 },
  { city: "Kabul", timezone: "Asia/Kabul", country: "AF", lat: 34.53, lng: 69.17 },
  { city: "Karachi", timezone: "Asia/Karachi", country: "PK", lat: 24.86, lng: 67.01 },
  { city: "Kathmandu", timezone: "Asia/Kathmandu", country: "NP", lat: 27.72, lng: 85.32 },
  { city: "Khartoum", timezone: "Africa/Khartoum", country: "SD", lat: 15.50, lng: 32.56 },
  { city: "Kinshasa", timezone: "Africa/Kinshasa", country: "CD", lat: -4.44, lng: 15.27 },
  { city: "Kuala Lumpur", timezone: "Asia/Kuala_Lumpur", country: "MY", lat: 3.14, lng: 101.69 },
  { city: "Kuwait City", timezone: "Asia/Kuwait", country: "KW", lat: 29.38, lng: 47.99 },
  { city: "Kyiv", timezone: "Europe/Kyiv", country: "UA", lat: 50.45, lng: 30.52 },
  { city: "Lagos", timezone: "Africa/Lagos", country: "NG", lat: 6.52, lng: 3.38 },
  { city: "Lahore", timezone: "Asia/Karachi", country: "PK", lat: 31.55, lng: 74.35 },
  { city: "La Paz", timezone: "America/La_Paz", country: "BO", lat: -16.50, lng: -68.15 },
  { city: "Lima", timezone: "America/Lima", country: "PE", lat: -12.05, lng: -77.04 },
  { city: "Lisbon", timezone: "Europe/Lisbon", country: "PT", lat: 38.72, lng: -9.14 },
  { city: "London", timezone: "Europe/London", country: "GB", lat: 51.51, lng: -0.13 },
  { city: "Los Angeles", timezone: "America/Los_Angeles", country: "US", lat: 34.05, lng: -118.24 },
  { city: "Luanda", timezone: "Africa/Luanda", country: "AO", lat: -8.84, lng: 13.23 },
  { city: "Madrid", timezone: "Europe/Madrid", country: "ES", lat: 40.42, lng: -3.70 },
  { city: "Manila", timezone: "Asia/Manila", country: "PH", lat: 14.60, lng: 120.98 },
  { city: "Maputo", timezone: "Africa/Maputo", country: "MZ", lat: -25.97, lng: 32.57 },
  { city: "Melbourne", timezone: "Australia/Melbourne", country: "AU", lat: -37.81, lng: 144.96 },
  { city: "Mexico City", timezone: "America/Mexico_City", country: "MX", lat: 19.43, lng: -99.13 },
  { city: "Miami", timezone: "America/New_York", country: "US", lat: 25.76, lng: -80.19 },
  { city: "Milan", timezone: "Europe/Rome", country: "IT", lat: 45.46, lng: 9.19 },
  { city: "Minneapolis", timezone: "America/Chicago", country: "US", lat: 44.98, lng: -93.27 },
  { city: "Minsk", timezone: "Europe/Minsk", country: "BY", lat: 53.90, lng: 27.57 },
  { city: "Montevideo", timezone: "America/Montevideo", country: "UY", lat: -34.88, lng: -56.16 },
  { city: "Montreal", timezone: "America/Toronto", country: "CA", lat: 45.50, lng: -73.57 },
  { city: "Moscow", timezone: "Europe/Moscow", country: "RU", lat: 55.76, lng: 37.62 },
  { city: "Mumbai", timezone: "Asia/Kolkata", country: "IN", lat: 19.08, lng: 72.88 },
  { city: "Munich", timezone: "Europe/Berlin", country: "DE", lat: 48.14, lng: 11.58 },
  { city: "Muscat", timezone: "Asia/Muscat", country: "OM", lat: 23.59, lng: 58.54 },
  { city: "Nairobi", timezone: "Africa/Nairobi", country: "KE", lat: -1.29, lng: 36.82 },
  { city: "New York", timezone: "America/New_York", country: "US", lat: 40.71, lng: -74.01 },
  { city: "Noumea", timezone: "Pacific/Noumea", country: "NC", lat: -22.28, lng: 166.46 },
  { city: "Novosibirsk", timezone: "Asia/Novosibirsk", country: "RU", lat: 55.04, lng: 82.93 },
  { city: "Osaka", timezone: "Asia/Tokyo", country: "JP", lat: 34.69, lng: 135.50 },
  { city: "Oslo", timezone: "Europe/Oslo", country: "NO", lat: 59.91, lng: 10.75 },
  { city: "Ottawa", timezone: "America/Toronto", country: "CA", lat: 45.42, lng: -75.70 },
  { city: "Panama City", timezone: "America/Panama", country: "PA", lat: 8.98, lng: -79.52 },
  { city: "Paris", timezone: "Europe/Paris", country: "FR", lat: 48.86, lng: 2.35 },
  { city: "Perth", timezone: "Australia/Perth", country: "AU", lat: -31.95, lng: 115.86 },
  { city: "Philadelphia", timezone: "America/New_York", country: "US", lat: 39.95, lng: -75.17 },
  { city: "Phnom Penh", timezone: "Asia/Phnom_Penh", country: "KH", lat: 11.56, lng: 104.92 },
  { city: "Phoenix", timezone: "America/Phoenix", country: "US", lat: 33.45, lng: -112.07 },
  { city: "Port Moresby", timezone: "Pacific/Port_Moresby", country: "PG", lat: -9.44, lng: 147.18 },
  { city: "Prague", timezone: "Europe/Prague", country: "CZ", lat: 50.08, lng: 14.42 },
  { city: "Pyongyang", timezone: "Asia/Pyongyang", country: "KP", lat: 39.02, lng: 125.75 },
  { city: "Quito", timezone: "America/Guayaquil", country: "EC", lat: -0.18, lng: -78.47 },
  { city: "Reykjavik", timezone: "Atlantic/Reykjavik", country: "IS", lat: 64.15, lng: -21.94 },
  { city: "Riga", timezone: "Europe/Riga", country: "LV", lat: 56.95, lng: 24.11 },
  { city: "Rio de Janeiro", timezone: "America/Sao_Paulo", country: "BR", lat: -22.91, lng: -43.17 },
  { city: "Riyadh", timezone: "Asia/Riyadh", country: "SA", lat: 24.69, lng: 46.72 },
  { city: "Rome", timezone: "Europe/Rome", country: "IT", lat: 41.90, lng: 12.50 },
  { city: "San Francisco", timezone: "America/Los_Angeles", country: "US", lat: 37.77, lng: -122.42 },
  { city: "San Juan", timezone: "America/Puerto_Rico", country: "PR", lat: 18.47, lng: -66.11 },
  { city: "San Salvador", timezone: "America/El_Salvador", country: "SV", lat: 13.69, lng: -89.19 },
  { city: "Santiago", timezone: "America/Santiago", country: "CL", lat: -33.45, lng: -70.67 },
  { city: "Santo Domingo", timezone: "America/Santo_Domingo", country: "DO", lat: 18.49, lng: -69.93 },
  { city: "Sao Paulo", timezone: "America/Sao_Paulo", country: "BR", lat: -23.55, lng: -46.63 },
  { city: "Seattle", timezone: "America/Los_Angeles", country: "US", lat: 47.61, lng: -122.33 },
  { city: "Seoul", timezone: "Asia/Seoul", country: "KR", lat: 37.57, lng: 126.98 },
  { city: "Shanghai", timezone: "Asia/Shanghai", country: "CN", lat: 31.23, lng: 121.47 },
  { city: "Singapore", timezone: "Asia/Singapore", country: "SG", lat: 1.35, lng: 103.82 },
  { city: "Sofia", timezone: "Europe/Sofia", country: "BG", lat: 42.70, lng: 23.32 },
  { city: "St. John's", timezone: "America/St_Johns", country: "CA", lat: 47.56, lng: -52.71 },
  { city: "Stockholm", timezone: "Europe/Stockholm", country: "SE", lat: 59.33, lng: 18.07 },
  { city: "Suva", timezone: "Pacific/Fiji", country: "FJ", lat: -18.14, lng: 178.44 },
  { city: "Sydney", timezone: "Australia/Sydney", country: "AU", lat: -33.87, lng: 151.21 },
  { city: "Taipei", timezone: "Asia/Taipei", country: "TW", lat: 25.03, lng: 121.57 },
  { city: "Tallinn", timezone: "Europe/Tallinn", country: "EE", lat: 59.44, lng: 24.75 },
  { city: "Tashkent", timezone: "Asia/Tashkent", country: "UZ", lat: 41.30, lng: 69.28 },
  { city: "Tbilisi", timezone: "Asia/Tbilisi", country: "GE", lat: 41.72, lng: 44.79 },
  { city: "Tehran", timezone: "Asia/Tehran", country: "IR", lat: 35.69, lng: 51.39 },
  { city: "Tel Aviv", timezone: "Asia/Jerusalem", country: "IL", lat: 32.08, lng: 34.78 },
  { city: "Tokyo", timezone: "Asia/Tokyo", country: "JP", lat: 35.68, lng: 139.69 },
  { city: "Toronto", timezone: "America/Toronto", country: "CA", lat: 43.65, lng: -79.38 },
  { city: "Tripoli", timezone: "Africa/Tripoli", country: "LY", lat: 32.90, lng: 13.18 },
  { city: "Tunis", timezone: "Africa/Tunis", country: "TN", lat: 36.81, lng: 10.17 },
  { city: "Ulaanbaatar", timezone: "Asia/Ulaanbaatar", country: "MN", lat: 47.91, lng: 106.91 },
  { city: "Vancouver", timezone: "America/Vancouver", country: "CA", lat: 49.28, lng: -123.12 },
  { city: "Vienna", timezone: "Europe/Vienna", country: "AT", lat: 48.21, lng: 16.37 },
  { city: "Vilnius", timezone: "Europe/Vilnius", country: "LT", lat: 54.69, lng: 25.28 },
  { city: "Warsaw", timezone: "Europe/Warsaw", country: "PL", lat: 52.23, lng: 21.01 },
  { city: "Washington DC", timezone: "America/New_York", country: "US", lat: 38.91, lng: -77.04 },
  { city: "Wellington", timezone: "Pacific/Auckland", country: "NZ", lat: -41.29, lng: 174.78 },
  { city: "Winnipeg", timezone: "America/Winnipeg", country: "CA", lat: 49.90, lng: -97.14 },
  { city: "Yangon", timezone: "Asia/Yangon", country: "MM", lat: 16.87, lng: 96.20 },
  { city: "Zagreb", timezone: "Europe/Zagreb", country: "HR", lat: 45.81, lng: 15.98 },
  { city: "Zurich", timezone: "Europe/Zurich", country: "CH", lat: 47.38, lng: 8.54 },
];
